#include "Assets/Util/Util.hlsl"

struct Agent
{
    float2 pos;
    float angle;
    int specieIndex;
    // float debug1;
    // float debug2;
    // float debug3;
};

struct Specie
{
    float moveSpeed;
    float turnSpeed;
    int dejavuTurn;
    float wanderIntensity;

    float3 mask;
    float sensorAngleOffset;
    float sensorDistanceOffset;
    int sensorSize;
        
    float3 color;
};

RWTexture2D<float4> TrailMap, DiffusedTrailMap;
float width, height, midX, midY, time, deltaTime, diffusionRate, trailWeight;
int trailSize;

RWStructuredBuffer<Agent> agents;
StructuredBuffer<Specie> species;

float sense(Agent agent, float sensorDegreeMultiplier)
{
    const Specie specie = species[agent.specieIndex];
    const float2 sensorMid = agent.pos + getDir(agent.angle + specie.sensorAngleOffset*sensorDegreeMultiplier) * specie.sensorDistanceOffset;
    const int sensorX = sensorMid.x;
    const int sensorY = sensorMid.y;
    // const int startX = limitWithinRange(sensorX-specie.sensorSize, 0, width);
    // const int endX = limitWithinRange(sensorX+specie.sensorSize, 0, width);
    // const int startY = limitWithinRange(sensorY-specie.sensorSize, 0, height);
    // const int endY = limitWithinRange(sensorY+specie.sensorSize, 0, height);
    float sum = 0;

    float4 senseWeight = float4(specie.color, 0);
    // float4 senseWeight = float4(specie.mask, 0);

    // const int startX = max(0, sensorMid.x - 3);
    // const int startY = max(0, sensorMid.y - 3);
    // const int endX = min(width, sensorMid.x + 3);
    // const int endY = min(height, sensorMid.y + 3);
    // for(int x = startX; x <= endX; ++x)
    // {
    //     for(int y = startY; y <= endY; ++y)
    //     {
    //         TrailMap[int2(x, y)] = float4(0, 1, 0, 1);
    //     }
    // }
    
    for(int offsetX = -specie.sensorSize; offsetX < specie.sensorSize; ++offsetX)
    {
        for(int offsetY = -specie.sensorSize; offsetY < specie.sensorSize; ++offsetY)
        {
            int sampleX = limitWithinRange(sensorX + offsetX, 0, width-1);
            int sampleY = limitWithinRange(sensorY + offsetY, 0, height-1);
            sum += dot(senseWeight, TrailMap[int2(sampleX, sampleY)]);
        }
    }
    
    return sum;
}

#pragma kernel Update

[numthreads(16,1,1)]
void Update(uint3 id : SV_DispatchThreadID)
{
    Agent agent = agents[id.x];
    const Specie specie = species[agent.specieIndex];
    
    const float random = scaleToRange01(hash(time+id.x));

    const float weightLeft = sense(agent, -1);
    const float weightForward = sense(agent, 0);
    const float weightRight = sense(agent, 1);
    const float sideWeight = max(weightLeft, weightRight);
    const bool sideZero = sideWeight <= 0;
    const float turnSpeed = specie.turnSpeed * (specie.dejavuTurn == 0 ? 1 : -1) * deltaTime;
    if(sideZero && weightForward <= 0)
        agent.angle += (random - 0.5) * turnSpeed * specie.wanderIntensity;
    else
    {
        if(weightForward > sideWeight)
        {
            
        }
        else if(!sideZero)
        {
            if(sideWeight == weightLeft)
                agent.angle = approachValue(agent.angle, agent.angle - specie.sensorAngleOffset, turnSpeed);
            else if(sideWeight == weightRight)
                agent.angle = approachValue(agent.angle, agent.angle + specie.sensorAngleOffset, turnSpeed);
        }
    }

    // if(weight == weightLeft)
    //     agent.angle -= turnSpeed*random;
    // else if(weight == weightRight)
    //     agent.angle += turnSpeed*random;
    
    // sideWeight = limitWithinRange(sqrt(sideWeight), 1, 1.523f);

    float2 direction = getDir(agent.angle);
    float2 newPos = agent.pos + direction * specie.moveSpeed * deltaTime;

    if(isOutside(newPos.x, newPos.y, width, height))
    {
        agent.angle = agent.angle - 200 + random*40;
        direction = getDir(agent.angle);
        newPos = agent.pos + direction * specie.moveSpeed * 3 * deltaTime;
    }
    // if(isOutside(newPos.x, newPos.y, width, height))
    //     newPos = float2(midX, midY);
    
    agent.pos = newPos;
    const int startX = max(0, agent.pos.x - trailSize);
    const int startY = max(0, agent.pos.y - trailSize);
    const int endX = min(width, agent.pos.x + trailSize);
    const int endY = min(height, agent.pos.y + trailSize);
    for(int x = startX; x <= endX; ++x)
    {
        for(int y = startY; y <= endY; ++y)
        {
            const int2 pixelPos = int2(x, y);
            const float3 oldTrail = TrailMap[pixelPos];
            TrailMap[pixelPos] = float4(min(1, oldTrail + specie.color * trailWeight * deltaTime), 1);
        }
    }
    
    // TrailMap[int2(agent.pos.x, agent.pos.y)] = float4(agent.angle%1, (agent.angle*1.5)%1, (agent.angle*2.25)%1, 1);
    // TrailMap[int2(agent.pos.x, agent.pos.y)] = float4((agent.angle*20)%1, newPos.x/width, newPos.y/height, 1);
    // TrailMap[int2(agent.pos.x, agent.pos.y)] = float4(agent.speed/1000, (agent.angle*agent.speed)%0.5, agent.speed/10000, 1);
    
    // float x = id.x / width;
    // float y = id.y / height;
    // Result[id.xy] = float4(sin(x), cos(x), tan(x + y), 1);
    
    agents[id.x] = agent;
}

#pragma kernel Diffuse

[numthreads(8,8,1)]
void Diffuse(uint3 id : SV_DispatchThreadID)
{
    const float4 originalCol = TrailMap[id.xy];
    float4 sum = 0;
    // 3x3 blur
    for(int offsetX = -1; offsetX <= 1; ++offsetX)
    {
        for(int offsetY = -1; offsetY <= 1; ++offsetY)
        {
            sum += TrailMap[int2
                (
                    limitWithinRange(id.x + offsetX, 0, width-1),
                    limitWithinRange(id.y + offsetY, 0, height-1)
                )];
        }
    }

    float4 blurredCol = sum / 9;
    const float diffuseWeight = saturate(diffusionRate * deltaTime);
    blurredCol = originalCol * (1 - diffuseWeight) + blurredCol * (diffuseWeight);
    float3 result = max(0, blurredCol - diffusionRate * deltaTime);
    DiffusedTrailMap[id.xy] = float4(result, 1);
}