// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

#include "Assets/Util/Util.hlsl"

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
float width;
float height;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float x = id.x / width;
    float y = id.y / height;
    Result[id.xy] = float4(x, y, (x + y) / 2.0, 1);
}
